CREATE TABLE GMEMBER(
   MID VARCHAR(20) PRIMARY KEY,
    MPW VARCHAR(20) NOT NULL,
    MANME VARCHAR(20) NOT NULL,
    MPHONE VARCHAR(50) NOT NULL,
    MPOSTCODE VARCHAR(100) NOT NULL,
    MADDRESS VARCHAR(100) NOT NULL,
    MDETAILADDRESS VARCHAR(200) NOT NULL,
    MEXTRAADDRESS VARCHAR(200) NOT NULL,
    ROLE VARCHAR(20) NOT NULL
);

CREATE TABLE REALTOR(
   RID VARCHAR(50) PRIMARY KEY,
    RPW VARCHAR(20) NOT NULL,
    RNAME VARCHAR(20) NOT NULL,
    RPHONE VARCHAR(20) NOT NULL,
    RPOSTCODE VARCHAR(50) NOT NULL,
    RADDRESS VARCHAR(200) NOT NULL,
    RDETAILADDRESS VARCHAR(200) NOT NULL,
    REXTRAADDRESS VARCHAR(200) NOT NULL,
    RCONSULTNUM INT NOT NULL,
    RMENT VARCHAR(200) NOT NULL
);

CREATE TABLE ESTATE(
   EPK INT PRIMARY KEY, 
    ENAME VARCHAR(20) NOT NULL, -- 이름
    PRICE VARCHAR(20) NOT NULL, -- 가격
    CATEGORY VARCHAR(20) NOT NULL, -- 건물 종류
    EADDRESS VARCHAR(200) NOT NULL, -- 주소   
    EINFO VARCHAR(200) NOT NULL, -- 평수
    EPAY VARCHAR(200) NOT NULL, -- 관리비
    SUBWAY VARCHAR(30) NOT NULL, -- 역
    RID VARCHAR(50) NOT NULL, -- 중개사pk
    EIMGSRC VARCHAR(400),
    CONSTRAINT E_RID FOREIGN KEY (RID) REFERENCES REALTOR(RID) ON DELETE CASCADE 
);
insert into realtor values(1,2,2,2,2,2,2,2,2,2);
insert into estate values ((SELECT NVL(MAX(EPK),0)+1 FROM ESTATE),1,2,2,2,2,2,'재양역',1,1);
SELECT * FROM ESTATE WHERE SUBWAY LIKE '%'||'양'||'%';

CREATE TABLE CONSULT(
	CID INT PRIMARY KEY,
	MID VARCHAR(20) NOT NULL,
	RID VARCHAR(20) NOT NULL,
	EPK INT NOT NULL,
	CDATE INT NOT NULL,
	CTIME INT NOT NULL,
	CONTENT VARCHAR(400) NOT NULL,
   	IMGSRC VARCHAR(50) NOT NULL,
    CONSTRAINT C_MID FOREIGN KEY (MID) REFERENCES GMEMBER(MID) ON DELETE CASCADE,
    CONSTRAINT C_RID FOREIGN KEY (RID) REFERENCES REALTOR(RID) ON DELETE CASCADE,
    CONSTRAINT C_EPK FOREIGN KEY (EPK) REFERENCES ESTATE(EPK) ON DELETE CASCADE
);

DROP TABLE CONSULT;

CREATE TABLE JJIM(
    JPK INT PRIMARY KEY,
    MID VARCHAR(20) NOT NULL,
    EPK INT NOT NULL,
    CONSTRAINT J_MID FOREIGN KEY (MID) REFERENCES GMEMBER(MID) ON DELETE CASCADE,
    CONSTRAINT J_EPK FOREIGN KEY (EPK) REFERENCES ESTATE(EPK) ON DELETE CASCADE
);